version: '3.8'

services:
  # Node.js Application Instances
  node1: 
    build: .
    container_name: node_app_1
    env_file: docker.local.props.env
    volumes:
      # - ./nodeApp:/myApp/nodeApp
    # working_dir: /myApp
      - /app/node_modules
    ports:
      - "3000:3000"
    environment: 
      - PORT=3000
      # - CHOKIDAR_USEPOLLING=true  # ‚Üê Add this
      # - WATCHPACK_POLLING=true
    networks:
      - load-balancing
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: nodemon --legacy-watch --polling-interval 1000 ./nodeApp/app.js
  
  node2: 
    build: .
    container_name: node_app_2
    env_file: docker.local.props.env
    # volumes:
      # - ./nodeApp:/myApp/nodeApp
    ports:
      - "3001:3001"
    environment: 
      - PORT=3001
    networks:
      - load-balancing
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: npx nodemon --watch src --watch config --watch routes ./nodeApp/app.js

  node3: 
    build: .
    container_name: node_app_3
    env_file: docker.local.props.env
    # volumes:
      # - ./nodeApp:/myApp/nodeApp
    ports:
      - "3002:3002"
    environment: 
      - PORT=3002
    networks:
      - load-balancing
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3  
    command: npx nodemon --watch src --watch config --watch routes ./nodeApp/app.js

  node4: 
    build: .
    container_name: node_app_4
    env_file: docker.local.props.env
    # volumes:
      # - ./nodeApp:/myApp/nodeApp
      # - ./:/myApp
    ports:
      - "3004:3004"
    environment: 
      - PORT=3004
    networks:
      - load-balancing 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3   
    command: npx nodemon --watch src --watch config --watch routes ./nodeApp/app.js     
    # command: nodemon --legacy-watch --polling-interval 1000 ./nodeApp/nodejsClusterLoadBalancing.js 
    # command: ["npm", "run", "cluster"]
  # Nginx Load Balancer
  nginx: 
    image: nginx:1.29.3-alpine
    container_name: nginx-load-balancer
    ports:
      - "80:80"
    volumes:
    - ./nginx:/etc/nginx/nginx.conf
    depends_on:
      - node1
      - node2
      - node3
    networks:
      - load-balancing
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  load-balancing:
    driver: bridge
volumes:
  nginx-data:

       
  
